name: build java and maven

on:
  push:
    branches: [MAIN]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       -  uses: actions/checkout@v4
       
       -  name: setup jdk 17
          uses: actions/setup-java@v4

       -   name: set up maven
           run: maven -B package --file pom.xml
        
